In [1]:
import pandas as pd

##### Series
##### What is a Series?
##### A Series is a one-dimensional Pandas data structure.
##### Think of it as a single column.

In [2]:
a = pd.Series([12,34,57,89,45,678])
print(a)

0     12
1     34
2     57
3     89
4     45
5    678
dtype: int64

#### DataFrame 
##### What is a DataFrame? 
##### A DataFrame is a two-dimensional table containing rows and columns. 
##### This is the structure you will use most often.

In [3]:
data = {
    "Name" : ["one","two","three"],
    "Age" :[12,34,56,],
    "Marks" :[12,45,75]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    one   12     12
1    two   34     45
2  three   56     75

In [4]:
df1 = pd.read_csv("Auto.csv") ## Reads a CSV file into a DataFrame.
## This is usually one of the first operations in a real ML project.

In [5]:
df1.head()
# Displays the first rows.
# By default it displays the first 5 rows.
# You can specify the number: df.head(10)
# To quickly understand what the dataset looks like.

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,customer_lifetime_value,is_repeat_customer,customer_order_count,PASSED,Bonus_Marks,Gender_code,Year,Month,Day,DayOfWeek
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,12459.68,True,11,True,5.5,1,2023,11,6,0
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,13032.48,True,11,False,2.6,1,2025,12,24,2
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,6159.44,True,6,True,6.9,0,2021,7,5,0
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,5638.30,True,7,True,6.5,1,2023,1,21,5
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,13240.10,True,8,True,3.4,0,2022,5,13,4

In [6]:
df1.tail()
# Useful for checking the end of the dataset.

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,customer_lifetime_value,is_repeat_customer,customer_order_count,PASSED,Bonus_Marks,Gender_code,Year,Month,Day,DayOfWeek
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,18182.63,True,14,True,4.1,0,2025,9,27,5
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,10004.74,True,10,True,4.0,1,2023,7,22,5
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,16442.68,True,15,True,3.9,0,2025,9,8,0
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,8047.00,True,5,True,4.6,0,2022,4,6,2
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,4107.38,True,5,False,2.8,1,2022,11,23,2

In [7]:
df1.shape
# This should be one of the first checks after loading a dataset.

(138116, 53)

In [8]:
df1.columns
# Shows the column names. 
# Useful for understanding available features and the target variable.

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer', 'customer_order_count',
       'PASSED', 'Bonus_Marks', 'Gender_code', 'Year', 'Month', 'Day',
       'DayOfWeek'],
      dtype='object')

In [9]:
df1.dtypes
# Shows the data type of each column.
# This helps identify: 
# Numerical columns
# Categorical columns 
# Date columns 
# Potential data-type problems

order_id                     object
order_date                   object
order_time                   object
order_status                 object
sales_channel                object
customer_id                  object
customer_name                object
customer_age                  int64
gender                       object
customer_segment             object
customer_type                object
customer_city                object
customer_state               object
customer_country             object
region                       object
customer_postal_code          int64
payment_method               object
payment_status               object
currency                     object
shipping_method              object
warehouse                    object
delivery_days               float64
estimated_delivery_days     float64
delivery_status              object
return_status                object
return_reason                object
customer_rating             float64
review_sentiment             object
customer_review              object
marketing_channel            object
campaign_name                object
coupon_code                  object
loyalty_points_earned         int64
loyalty_points_redeemed       int64
quantity                      int64
gross_sales                 float64
discount_amount             float64
tax_amount                  float64
shipping_cost               float64
net_sales                     int64
product_cost                float64
profit                      float64
profit_margin_percentage    float64
customer_lifetime_value     float64
is_repeat_customer             bool
customer_order_count          int64
PASSED                         bool
Bonus_Marks                 float64
Gender_code                   int64
Year                          int64
Month                         int64
Day                           int64
DayOfWeek                     int64
dtype: object

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 53 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  object
 2   order_time                138116 non-null  object
 3   order_status              138116 non-null  object
 4   sales_channel             138116 non-null  object
 5   customer_id               138116 non-null  object
 6   customer_name             138116 non-null  object
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  object
 9   customer_segment          138116 non-null  object
 10  customer_type             138116 non-null  object
 11  customer_city             138116 non-null  object
 12  customer_state            138116 non-null  object
 13  customer_country          138116 non-null  object
 14  region                    138116 non-null  object
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  object
 17  payment_status            138116 non-null  object
 18  currency                  138116 non-null  object
 19  shipping_method           138116 non-null  object
 20  warehouse                 138116 non-null  object
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  object
 24  return_status             9462 non-null    object
 25  return_reason             9462 non-null    object
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  int64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
 46  PASSED                    138116 non-null  bool
 47  Bonus_Marks               138116 non-null  float64
 48  Gender_code               138116 non-null  int64
 49  Year                      138116 non-null  int64
 50  Month                     138116 non-null  int64
 51  Day                       138116 non-null  int64
 52  DayOfWeek                 138116 non-null  int64
dtypes: bool(2), float64(12), int64(12), object(27)
memory usage: 54.0+ MB

In [11]:
df1.describe()
# Provides statistical information for numerical columns: 
# Count 
# Mean 
# Standard deviation 
# Minimum 
# 25% 
# Median 
# 75% 
# Maximum 
# This is extremely useful during EDA.

,customer_age,customer_postal_code,delivery_days,estimated_delivery_days,customer_rating,loyalty_points_earned,loyalty_points_redeemed,quantity,gross_sales,discount_amount,...,profit,profit_margin_percentage,customer_lifetime_value,customer_order_count,Bonus_Marks,Gender_code,Year,Month,Day,DayOfWeek
count,138116.000000,138116.000000,113559.000000,113559.000000,113559.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,...,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000,138116.000000
mean,45.862681,50210.889310,4.557772,4.298875,3.677015,103.991051,51.934128,5.615244,1375.384176,237.621614,...,551.322046,45.065997,8971.639047,6.990559,4.586268,0.597056,2023.002114,7.125272,15.751535,2.995135
std,16.467676,28569.767779,2.810012,2.594080,0.483672,115.175640,73.217692,3.371289,1291.009554,378.779459,...,516.300936,13.120357,4430.506588,2.444166,1.646768,0.689104,1.413469,3.528313,8.789446,1.998611
min,18.000000,516.000000,0.000000,0.000000,1.600000,0.000000,0.000000,1.000000,6.310000,0.000000,...,-1281.590000,-59.550000,22.550000,1.000000,1.800000,0.000000,2021.000000,1.000000,1.000000,0.000000
25%,32.000000,25509.000000,2.000000,2.000000,3.400000,17.000000,3.000000,3.000000,458.920000,26.327500,...,190.757500,38.880000,5713.570000,5.000000,3.200000,0.000000,2022.000000,4.000000,8.000000,1.000000
50%,46.000000,50183.000000,4.000000,4.000000,3.700000,70.000000,25.000000,5.000000,995.730000,103.285000,...,408.395000,46.990000,8392.525000,7.000000,4.600000,1.000000,2023.000000,7.000000,16.000000,3.000000
75%,60.000000,74898.000000,7.000000,6.000000,4.000000,151.000000,71.000000,8.000000,1871.200000,277.125000,...,752.845000,53.770000,11651.030000,9.000000,6.000000,1.000000,2024.000000,10.000000,23.000000,5.000000
max,74.000000,99950.000000,14.000000,10.000000,5.000000,1621.000000,1063.000000,24.000000,16051.190000,6759.020000,...,7083.680000,77.590000,30268.440000,20.000000,7.400000,3.000000,2025.000000,12.000000,31.000000,6.000000

In [13]:
df1["coupon_code"] #reutrns one columns

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
           ...
138111       NaN
138112       NaN
138113       NaN
138114    SAVE39
138115       NaN
Name: coupon_code, Length: 138116, dtype: object

In [17]:
df1[["Bonus_Marks","Year"]] #returns more then one columns

        Bonus_Marks  Year
0               5.5  2023
1               2.6  2025
2               6.9  2021
3               6.5  2023
4               3.4  2022
...             ...   ...
138111          4.1  2025
138112          4.0  2023
138113          3.9  2025
138114          4.6  2022
138115          2.8  2022

[138116 rows x 2 columns]

In [18]:
# df.loc[0] #loc selects rows/columns using labels.
df1.loc[:,["Year","Bonus_Marks"]] #You can also select specific columns:

        Year  Bonus_Marks
0       2023          5.5
1       2025          2.6
2       2021          6.9
3       2023          6.5
4       2022          3.4
...      ...          ...
138111  2025          4.1
138112  2023          4.0
138113  2025          3.9
138114  2022          4.6
138115  2022          2.8

[138116 rows x 2 columns]

In [19]:
# df.iloc[0] #To print First Row
df1.iloc[0:6] # TO print 0 to 6 numbers rows

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,customer_lifetime_value,is_repeat_customer,customer_order_count,PASSED,Bonus_Marks,Gender_code,Year,Month,Day,DayOfWeek
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,12459.68,True,11,True,5.5,1,2023,11,6,0
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,13032.48,True,11,False,2.6,1,2025,12,24,2
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,6159.44,True,6,True,6.9,0,2021,7,5,0
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,5638.30,True,7,True,6.5,1,2023,1,21,5
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,13240.10,True,8,True,3.4,0,2022,5,13,4
5,ORD-208728,2021-02-10,10:05:47,Pending,Website,CUST-021468,Dominique Odom,41,Female,Consumer,...,5615.09,True,3,True,4.1,0,2021,2,10,2

In [20]:
df1[df1["Bonus_Marks"]>40] #This returns mpg whose marks are greater than 40.

Empty DataFrame
Columns: [order_id, order_date, order_time, order_status, sales_channel, customer_id, customer_name, customer_age, gender, customer_segment, customer_type, customer_city, customer_state, customer_country, region, customer_postal_code, payment_method, payment_status, currency, shipping_method, warehouse, delivery_days, estimated_delivery_days, delivery_status, return_status, return_reason, customer_rating, review_sentiment, customer_review, marketing_channel, campaign_name, coupon_code, loyalty_points_earned, loyalty_points_redeemed, quantity, gross_sales, discount_amount, tax_amount, shipping_cost, net_sales, product_cost, profit, profit_margin_percentage, customer_lifetime_value, is_repeat_customer, customer_order_count, PASSED, Bonus_Marks, Gender_code, Year, Month, Day, DayOfWeek]
Index: []

[0 rows x 53 columns]

In [22]:
df1[
    (df1["Bonus_Marks"]>40)&
    (df1["customer_lifetime_value"]>400)
]
# &   → AND
# |   → OR
#  ~   → NOT

Empty DataFrame
Columns: [order_id, order_date, order_time, order_status, sales_channel, customer_id, customer_name, customer_age, gender, customer_segment, customer_type, customer_city, customer_state, customer_country, region, customer_postal_code, payment_method, payment_status, currency, shipping_method, warehouse, delivery_days, estimated_delivery_days, delivery_status, return_status, return_reason, customer_rating, review_sentiment, customer_review, marketing_channel, campaign_name, coupon_code, loyalty_points_earned, loyalty_points_redeemed, quantity, gross_sales, discount_amount, tax_amount, shipping_cost, net_sales, product_cost, profit, profit_margin_percentage, customer_lifetime_value, is_repeat_customer, customer_order_count, PASSED, Bonus_Marks, Gender_code, Year, Month, Day, DayOfWeek]
Index: []

[0 rows x 53 columns]

In [ ]:
# value_counts()
# What does it do?
# Counts how frequently each value occurs
# df["Gender"].value_counts()
# it makes easy to count values
# like male female and other thing
# Very useful for categorical data. 
# It can also help inspect class imbalance in classification problems.

In [23]:
df = pd.read_csv("ecommerce_sales_customer_analytics_150k.csv")

In [24]:
df.value_counts("gender")

gender
Female        66439
Male          66284
Non-Binary     5393
Name: count, dtype: int64

In [25]:
df["gender"].unique()

array(['Male', 'Female', 'Non-Binary'], dtype=object)

In [26]:
df["gender"].nunique() #Counts the number of unique values.
#Useful for understanding categorical columns and identifiers.

3

In [27]:
df.isnull()
#Returns True/False for missing values.

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138112,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138113,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138114,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138115,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [28]:
df.isnull().sum()
#want the count:

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [29]:
# df.notnull() #Checks values that are not missing.
df.notnull().sum() #Useful when filtering valid records.

order_id                    138116
order_date                  138116
order_time                  138116
order_status                138116
sales_channel               138116
customer_id                 138116
customer_name               138116
customer_age                138116
gender                      138116
customer_segment            138116
customer_type               138116
customer_city               138116
customer_state              138116
customer_country            138116
region                      138116
customer_postal_code        138116
payment_method              138116
payment_status              138116
currency                    138116
shipping_method             138116
warehouse                   138116
delivery_days               113559
estimated_delivery_days     113559
delivery_status             138116
return_status                 9462
return_reason                 9462
customer_rating             113559
review_sentiment            113559
customer_review             113559
marketing_channel           138116
campaign_name                54883
coupon_code                  27614
loyalty_points_earned       138116
loyalty_points_redeemed     138116
quantity                    138116
gross_sales                 138116
discount_amount             138116
tax_amount                  138116
shipping_cost               138116
net_sales                   138116
product_cost                138116
profit                      138116
profit_margin_percentage    138116
customer_lifetime_value     138116
is_repeat_customer          138116
customer_order_count        138116
dtype: int64

In [30]:
clear_data = df.dropna() #Removes rows/columns containing missing values.

In [31]:
clear_data

Empty DataFrame
Columns: [order_id, order_date, order_time, order_status, sales_channel, customer_id, customer_name, customer_age, gender, customer_segment, customer_type, customer_city, customer_state, customer_country, region, customer_postal_code, payment_method, payment_status, currency, shipping_method, warehouse, delivery_days, estimated_delivery_days, delivery_status, return_status, return_reason, customer_rating, review_sentiment, customer_review, marketing_channel, campaign_name, coupon_code, loyalty_points_earned, loyalty_points_redeemed, quantity, gross_sales, discount_amount, tax_amount, shipping_cost, net_sales, product_cost, profit, profit_margin_percentage, customer_lifetime_value, is_repeat_customer, customer_order_count]
Index: []

[0 rows x 46 columns]

In [32]:
df.fillna
# df["Age"] = df["Age"].fillna(df["Age"].median())
# df["Age"].fillna(25)
# df["City"].fillna("Unknown")

<bound method NDFrame.fillna of           order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]>

In [33]:
df.duplicated

<bound method DataFrame.duplicated of           order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]>

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df = df.drop_duplicates()
#Useful during data cleaning when duplicate records are not valid observations.

In [36]:
df.sort_values("gender", ascending=False)
#Useful for ranking and exploring data.

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
68608,ORD-845420,2024-10-04,20:14:19,Completed,Mobile App,CUST-021493,Craig Hays,63,Non-Binary,Consumer,...,213.41,117.40,63.48,1857.95,1105.80,688.67,37.07,2703.31,True,4
11804,ORD-732492,2025-11-17,14:10:58,Completed,Marketplace,CUST-006428,Jesse Henry,50,Non-Binary,Consumer,...,611.50,312.01,20.21,1892.27,977.61,894.45,47.27,7816.90,True,5
60227,ORD-224540,2023-07-15,11:59:45,Completed,Website,CUST-010088,Melissa Martinez,29,Non-Binary,Consumer,...,376.70,355.39,44.37,2270.20,1030.02,1195.81,52.67,9024.98,True,8
44733,ORD-835608,2024-01-29,00:03:36,Completed,Mobile App,CUST-004857,Maria Peterson,59,Non-Binary,Consumer,...,79.26,67.64,11.62,1045.55,527.34,506.59,48.45,4335.14,True,5
28436,ORD-370015,2021-02-18,14:59:35,Completed,Website,CUST-000540,Carmen Jennings,41,Non-Binary,Consumer,...,517.31,249.32,15.32,3826.31,2554.38,1256.61,32.84,14582.06,True,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82692,ORD-967872,2024-04-01,02:29:19,Completed,Marketplace,CUST-021795,Kevin Carter,63,Female,Consumer,...,0.69,18.01,29.23,304.51,129.08,146.20,48.01,11718.00,True,8
29766,ORD-401076,2021-09-16,14:26:04,Completed,Website,CUST-013620,Michael Clark,31,Female,Consumer,...,85.98,132.87,28.10,825.28,319.65,477.53,57.86,4783.03,True,3
29767,ORD-860832,2023-11-15,16:39:23,Completed,Mobile App,CUST-004798,Katelyn Clark,37,Female,Consumer,...,85.64,15.31,33.37,354.93,198.30,123.26,34.73,8017.49,True,11
82689,ORD-467417,2024-06-02,19:16:27,Completed,Social Media,CUST-009429,Cheryl Franco,26,Female,Business,...,3.27,68.22,23.11,450.39,162.09,265.19,58.88,8338.60,True,8
69058,ORD-537741,2023-06-24,14:49:19,Completed,Mobile App,CUST-002601,Joseph Jones,47,Female,Premium,...,274.50,82.52,18.38,1279.80,542.76,718.66,56.15,11136.13,True,9

In [37]:
df["customer_age"].mean()
# These are useful for understanding numerical variables.

np.float64(45.86268064525471)

In [38]:
df["customer_age"].median()

46.0

In [39]:
df["customer_age"].std()

16.46767571607873

In [40]:
df["customer_age"].min()

18

In [41]:
df["customer_age"].max()

74

In [42]:
df.groupby("gender")["customer_age"].mean()
#What does it do? 
#Groups data based on a column and allows calculations for each group.

gender
Female        45.815094
Male          45.875460
Non-Binary    46.291860
Name: customer_age, dtype: float64

In [69]:
df.groupby("gender")["customer_age"].agg(
    ["mean","median","min","max"]
)
#Useful for comparing groups.

                 mean  median  min  max
gender
Female      45.815094    46.0   18   74
Male        45.875460    46.0   18   74
Non-Binary  46.291860    46.0   18   74

In [44]:
df["customer_age"].agg(["mean","median","min","max"])
#Allows multiple aggregation operations

mean      45.862681
median    46.000000
min       18.000000
max       74.000000
Name: customer_age, dtype: float64

In [45]:
# Creating a New Column
# What does it do? 
# Creates a derived feature
df["passed"] = df["customer_age"] >= 30

In [46]:
df["passed"]

0          True
1         False
2          True
3          True
4          True
          ...
138111     True
138112     True
138113     True
138114     True
138115    False
Name: passed, Length: 138116, dtype: bool

In [47]:
df["Bonus_Marks"] = df["customer_age"] * 0.10
#This creates a new feature based on an existing feature.

In [48]:
df["Bonus_Marks"]

0         5.5
1         2.6
2         6.9
3         6.5
4         3.4
         ...
138111    4.1
138112    4.0
138113    3.9
138114    4.6
138115    2.8
Name: Bonus_Marks, Length: 138116, dtype: float64

In [49]:
df["Gender_code"] = df["gender"].map({
    "Male":1,
    "Female":0,
    "Non-Binary":3
})

In [50]:
df["Gender_code"]

0         1
1         1
2         0
3         1
4         0
         ..
138111    0
138112    1
138113    0
138114    0
138115    1
Name: Gender_code, Length: 138116, dtype: int64

In [51]:
# astype()
# Changes data type.
# Useful when a column has an incorrect or unsuitable type.
df["net_sales"] = df["net_sales"].astype(int)

In [52]:
df["net_sales"]

0          945
1         2018
2          468
3          546
4         2785
          ...
138111     224
138112    2260
138113    2261
138114    2080
138115    1572
Name: net_sales, Length: 138116, dtype: int64

In [53]:
# pd.to_datetime() 
# Converts a column to datetime.
# This is important when working with: (1) Sales data ,(2)Transactions ,(3)Trips, (4)Time, (5)series, (6)Logs
df["order_date"] = pd.to_datetime(df["order_date"])

In [54]:
df["order_date"]

0        2023-11-06
1        2025-12-24
2        2021-07-05
3        2023-01-21
4        2022-05-13
            ...
138111   2025-09-27
138112   2023-07-22
138113   2025-09-08
138114   2022-04-06
138115   2022-11-23
Name: order_date, Length: 138116, dtype: datetime64[ns]

In [55]:
df["Year"] = df["order_date"].dt.year
df["Month"] = df["order_date"].dt.month
df["Day"] = df["order_date"].dt.day
df["DayOfWeek"] = df["order_date"].dt.dayofweek
#This is another example of feature engineering.
# Each Df gives differnt values like if we call year it will show us years so we dont see unnecessary data
# if we call df month it will only show us months data

In [56]:
# df["Year"]
df["Day"]

0          6
1         24
2          5
3         21
4         13
          ..
138111    27
138112    22
138113     8
138114     6
138115    23
Name: Day, Length: 138116, dtype: int32

In [57]:
#  drop()
# Removes columns or rows.
# df = df.drop(["pass"], axis=1)

In [58]:
df

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,customer_lifetime_value,is_repeat_customer,customer_order_count,passed,Bonus_Marks,Gender_code,Year,Month,Day,DayOfWeek
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,12459.68,True,11,True,5.5,1,2023,11,6,0
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,13032.48,True,11,False,2.6,1,2025,12,24,2
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,6159.44,True,6,True,6.9,0,2021,7,5,0
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,5638.30,True,7,True,6.5,1,2023,1,21,5
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,13240.10,True,8,True,3.4,0,2022,5,13,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,18182.63,True,14,True,4.1,0,2025,9,27,5
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,10004.74,True,10,True,4.0,1,2023,7,22,5
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,16442.68,True,15,True,3.9,0,2025,9,8,0
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,8047.00,True,5,True,4.6,0,2022,4,6,2
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,4107.38,True,5,False,2.8,1,2022,11,23,2

In [59]:
# rename()
# Changes column names.
# Useful for creating clear and consistent feature names.
df = df.rename(columns={
    "passed" : "PASSED"
})

In [60]:
df

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,customer_lifetime_value,is_repeat_customer,customer_order_count,PASSED,Bonus_Marks,Gender_code,Year,Month,Day,DayOfWeek
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,12459.68,True,11,True,5.5,1,2023,11,6,0
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,13032.48,True,11,False,2.6,1,2025,12,24,2
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,6159.44,True,6,True,6.9,0,2021,7,5,0
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,5638.30,True,7,True,6.5,1,2023,1,21,5
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,13240.10,True,8,True,3.4,0,2022,5,13,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,ORD-481534,2025-09-27,13:00:50,Completed,Mobile App,CUST-007151,Donna Ruiz,41,Female,Consumer,...,18182.63,True,14,True,4.1,0,2025,9,27,5
138112,ORD-487614,2023-07-22,09:13:25,Returned,Social Media,CUST-006686,Jeremy Aguirre,40,Male,Premium,...,10004.74,True,10,True,4.0,1,2023,7,22,5
138113,ORD-248062,2025-09-08,18:30:32,Cancelled,Mobile App,CUST-017497,Timothy Williams,39,Female,Consumer,...,16442.68,True,15,True,3.9,0,2025,9,8,0
138114,ORD-252033,2022-04-06,14:50:07,Completed,Social Media,CUST-005723,Charles Hanson,46,Female,Consumer,...,8047.00,True,5,True,4.6,0,2022,4,6,2
138115,ORD-528577,2022-11-23,11:46:00,Completed,Mobile App,CUST-006809,John Miller,28,Male,Consumer,...,4107.38,True,5,False,2.8,1,2022,11,23,2

In [61]:
combined = pd.concat([df1,df])

In [64]:
combined["customer_lifetime_value"]

0         12459.68
1         13032.48
2          6159.44
3          5638.30
4         13240.10
            ...
138111    18182.63
138112    10004.74
138113    16442.68
138114     8047.00
138115     4107.38
Name: customer_lifetime_value, Length: 276232, dtype: float64

In [63]:
# merge = pd.merge(
#     customer_order_count,
#     is_repeat_customer,
#     on="New_ID"
# )
# This is useful when information is spread across multiple tables.

In [ ]:
# corr() 
# What does it do?
# Calculates correlation between numerical columns.
# Correlation helps investigate relationships between numerical variables. 
# Later it becomes useful when studying:
#  Feature relationships
#  Multicollinearity
# Feature selection
df.corr

<bound method DataFrame.corr of           order_id order_date order_time order_status sales_channel  \
0       ORD-301242 2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460 2025-12-24   01:22:36    Completed       Website
2       ORD-449374 2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636 2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028 2022-05-13   09:46:21    Completed  Social Media
...            ...        ...        ...          ...           ...
138111  ORD-481534 2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614 2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062 2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033 2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577 2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... customer_lifetime_value is_repeat_customer customer_order_count  \
0       ...                12459.68               True                   11
1       ...                13032.48               True                   11
2       ...                 6159.44               True                    6
3       ...                 5638.30               True                    7
4       ...                13240.10               True                    8
...     ...                     ...                ...                  ...
138111  ...                18182.63               True                   14
138112  ...                10004.74               True                   10
138113  ...                16442.68               True                   15
138114  ...                 8047.00               True                    5
138115  ...                 4107.38               True                    5

       PASSED Bonus_Marks  Gender_code  Year Month Day DayOfWeek
0        True         5.5            1  2023    11   6         0
1       False         2.6            1  2025    12  24         2
2        True         6.9            0  2021     7   5         0
3        True         6.5            1  2023     1  21         5
4        True         3.4            0  2022     5  13         4
...       ...         ...          ...   ...   ...  ..       ...
138111   True         4.1            0  2025     9  27         5
138112   True         4.0            1  2023     7  22         5
138113   True         3.9            0  2025     9   8         0
138114   True         4.6            0  2022     4   6         2
138115  False         2.8            1  2022    11  23         2

[138116 rows x 53 columns]>

In [67]:
# to_csv()
# Saves a DataFrame as CSV.
# df.to_csv("Auto.csv", index=False)

In [68]:
# to_excel()
# Saves a DataFrame as Excel.
# df.to_excel("Auto.xlsx", index=False)