In [1]:
import pandas as pd

##### Series
##### What is a Series?
##### A Series is a one-dimensional Pandas data structure.
##### Think of it as a single column.

In [2]:
a = pd.Series([12,34,57,89,45,678])
print(a)

0     12
1     34
2     57
3     89
4     45
5    678
dtype: int64

#### DataFrame 
##### What is a DataFrame? 
##### A DataFrame is a two-dimensional table containing rows and columns. 
##### This is the structure you will use most often.

In [3]:
data = {
    "Name" : ["one","two","three"],
    "Age" :[12,34,56,],
    "Marks" :[12,45,75]
}
df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0    one   12     12
1    two   34     45
2  three   56     75

In [4]:
df = pd.read_csv("Auto.csv") ## Reads a CSV file into a DataFrame.
## This is usually one of the first operations in a real ML project.

In [5]:
df.head()
# Displays the first rows.
# By default it displays the first 5 rows.
# You can specify the number: df.head(10)
# To quickly understand what the dataset looks like.

    mpg  weight
0  18.0    3504
1  15.0    3693
2  18.0    3436
3  16.0    3433
4  17.0    3449

In [6]:
df.tail()
# Useful for checking the end of the dataset.

      mpg  weight
295  25.4    3530
296  23.0    3900
297  27.2    3190
298  23.9    3420
299  34.2    2200

In [7]:
df.shape
# This should be one of the first checks after loading a dataset.

(300, 2)

In [8]:
df.columns
# Shows the column names. 
# Useful for understanding available features and the target variable.

Index(['mpg', 'weight'], dtype='object')

In [9]:
df.dtypes
# Shows the data type of each column.
# This helps identify: 
# Numerical columns
# Categorical columns 
# Date columns 
# Potential data-type problems

mpg       float64
weight      int64
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mpg     300 non-null    float64
 1   weight  300 non-null    int64
dtypes: float64(1), int64(1)
memory usage: 4.8 KB

In [11]:
df.describe()
# Provides statistical information for numerical columns: 
# Count 
# Mean 
# Standard deviation 
# Minimum 
# 25% 
# Median 
# 75% 
# Maximum 
# This is extremely useful during EDA.

              mpg       weight
count  300.000000   300.000000
mean    20.839333  3135.330000
std      6.330712   883.902453
min      9.000000  1613.000000
25%     16.000000  2297.000000
50%     20.000000  3111.500000
75%     25.025000  3855.000000
max     43.100000  5140.000000

In [12]:
df["mpg"] #reutrns one columns

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
295    25.4
296    23.0
297    27.2
298    23.9
299    34.2
Name: mpg, Length: 300, dtype: float64

In [13]:
df[["mpg","weight"]] #returns more then one columns

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
295  25.4    3530
296  23.0    3900
297  27.2    3190
298  23.9    3420
299  34.2    2200

[300 rows x 2 columns]

In [14]:
# df.loc[0] #loc selects rows/columns using labels.
df.loc[:,["mpg","weight"]] #You can also select specific columns:

      mpg  weight
0    18.0    3504
1    15.0    3693
2    18.0    3436
3    16.0    3433
4    17.0    3449
..    ...     ...
295  25.4    3530
296  23.0    3900
297  27.2    3190
298  23.9    3420
299  34.2    2200

[300 rows x 2 columns]

In [15]:
# df.iloc[0] #To print First Row
df.iloc[0:6] # TO print 0 to 6 numbers rows

    mpg  weight
0  18.0    3504
1  15.0    3693
2  18.0    3436
3  16.0    3433
4  17.0    3449
5  15.0    4341

In [16]:
df[df["mpg"]>40] #This returns mpg whose marks are greater than 40.

      mpg  weight
242  43.1    1985

In [17]:
df[
    (df["mpg"]>40)&
    (df["weight"]>400)
]
# &   → AND
# |   → OR
#  ~   → NOT

      mpg  weight
242  43.1    1985

In [18]:
# value_counts()
# What does it do?
# Counts how frequently each value occurs
# df["Gender"].value_counts()
# it makes easy to count values
# like male female and other thing
# Very useful for categorical data. 
# It can also help inspect class imbalance in classification problems.

In [19]:
df = pd.read_csv("ecommerce_sales_customer_analytics_150k.csv")

In [20]:
df.value_counts("gender")

gender
Female        66439
Male          66284
Non-Binary     5393
Name: count, dtype: int64

In [21]:
df["gender"].unique()

array(['Male', 'Female', 'Non-Binary'], dtype=object)

In [22]:
df["gender"].nunique() #Counts the number of unique values.
#Useful for understanding categorical columns and identifiers.

3

In [23]:
df.isnull()
#Returns True/False for missing values.

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138111,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138112,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138113,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138114,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138115,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
df.isnull().sum()
#want the count:

order_id                         0
order_date                       0
order_time                       0
order_status                     0
sales_channel                    0
customer_id                      0
customer_name                    0
customer_age                     0
gender                           0
customer_segment                 0
customer_type                    0
customer_city                    0
customer_state                   0
customer_country                 0
region                           0
customer_postal_code             0
payment_method                   0
payment_status                   0
currency                         0
shipping_method                  0
warehouse                        0
delivery_days                24557
estimated_delivery_days      24557
delivery_status                  0
return_status               128654
return_reason               128654
customer_rating              24557
review_sentiment             24557
customer_review              24557
marketing_channel                0
campaign_name                83233
coupon_code                 110502
loyalty_points_earned            0
loyalty_points_redeemed          0
quantity                         0
gross_sales                      0
discount_amount                  0
tax_amount                       0
shipping_cost                    0
net_sales                        0
product_cost                     0
profit                           0
profit_margin_percentage         0
customer_lifetime_value          0
is_repeat_customer               0
customer_order_count             0
dtype: int64

In [25]:
# df.notnull() #Checks values that are not missing.
df.notnull().sum() #Useful when filtering valid records.

order_id                    138116
order_date                  138116
order_time                  138116
order_status                138116
sales_channel               138116
customer_id                 138116
customer_name               138116
customer_age                138116
gender                      138116
customer_segment            138116
customer_type               138116
customer_city               138116
customer_state              138116
customer_country            138116
region                      138116
customer_postal_code        138116
payment_method              138116
payment_status              138116
currency                    138116
shipping_method             138116
warehouse                   138116
delivery_days               113559
estimated_delivery_days     113559
delivery_status             138116
return_status                 9462
return_reason                 9462
customer_rating             113559
review_sentiment            113559
customer_review             113559
marketing_channel           138116
campaign_name                54883
coupon_code                  27614
loyalty_points_earned       138116
loyalty_points_redeemed     138116
quantity                    138116
gross_sales                 138116
discount_amount             138116
tax_amount                  138116
shipping_cost               138116
net_sales                   138116
product_cost                138116
profit                      138116
profit_margin_percentage    138116
customer_lifetime_value     138116
is_repeat_customer          138116
customer_order_count        138116
dtype: int64

In [26]:
clear_data = df.dropna() #Removes rows/columns containing missing values.

In [27]:
clear_data

Empty DataFrame
Columns: [order_id, order_date, order_time, order_status, sales_channel, customer_id, customer_name, customer_age, gender, customer_segment, customer_type, customer_city, customer_state, customer_country, region, customer_postal_code, payment_method, payment_status, currency, shipping_method, warehouse, delivery_days, estimated_delivery_days, delivery_status, return_status, return_reason, customer_rating, review_sentiment, customer_review, marketing_channel, campaign_name, coupon_code, loyalty_points_earned, loyalty_points_redeemed, quantity, gross_sales, discount_amount, tax_amount, shipping_cost, net_sales, product_cost, profit, profit_margin_percentage, customer_lifetime_value, is_repeat_customer, customer_order_count]
Index: []

[0 rows x 46 columns]

In [ ]:
df.fillna
# df["Age"] = df["Age"].fillna(df["Age"].median())
# df["Age"].fillna(25)
# df["City"].fillna("Unknown")

<bound method NDFrame.fillna of           order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]>

In [34]:
df.duplicated

<bound method DataFrame.duplicated of           order_id  order_date order_time order_status sales_channel  \
0       ORD-301242  2023-11-06   16:37:47    Completed    Mobile App
1       ORD-773460  2025-12-24   01:22:36    Completed       Website
2       ORD-449374  2021-07-05   14:24:21    Completed    Mobile App
3       ORD-567636  2023-01-21   07:20:26    Completed  Social Media
4       ORD-820028  2022-05-13   09:46:21    Completed  Social Media
...            ...         ...        ...          ...           ...
138111  ORD-481534  2025-09-27   13:00:50    Completed    Mobile App
138112  ORD-487614  2023-07-22   09:13:25     Returned  Social Media
138113  ORD-248062  2025-09-08   18:30:32    Cancelled    Mobile App
138114  ORD-252033  2022-04-06   14:50:07    Completed  Social Media
138115  ORD-528577  2022-11-23   11:46:00    Completed    Mobile App

        customer_id     customer_name  customer_age  gender customer_segment  \
0       CUST-003102      Jasmine Ryan            55    Male         Consumer
1       CUST-003124       Scott Chase            26    Male          Premium
2       CUST-012496      Marc Wheeler            69  Female          Premium
3       CUST-023928    Jennifer Smith            65    Male         Consumer
4       CUST-012730      Jessica Wang            34  Female         Consumer
...             ...               ...           ...     ...              ...
138111  CUST-007151        Donna Ruiz            41  Female         Consumer
138112  CUST-006686    Jeremy Aguirre            40    Male          Premium
138113  CUST-017497  Timothy Williams            39  Female         Consumer
138114  CUST-005723    Charles Hanson            46  Female         Consumer
138115  CUST-006809       John Miller            28    Male         Consumer

        ... discount_amount tax_amount shipping_cost net_sales product_cost  \
0       ...          477.89      61.07         12.03    945.40       588.33
1       ...         1456.06     320.83          9.00   2018.41      2031.88
2       ...           97.30      29.79         13.05    468.35       257.73
3       ...           53.34      34.39         20.85    546.52       277.84
4       ...          133.63     421.35         23.03   2785.27      1231.88
...     ...             ...        ...           ...       ...          ...
138111  ...            8.84      14.28          6.15    224.42       101.77
138112  ...            0.00     147.30          9.18   2260.80      1246.73
138113  ...            0.00     372.37         26.94   2261.16       970.95
138114  ...          174.60     130.58         84.39   2080.38      1042.40
138115  ...          417.27     102.26          9.09   1572.22       884.46

         profit profit_margin_percentage customer_lifetime_value  \
0        345.04                    36.50                12459.68
1        -22.47                    -1.11                13032.48
2        197.57                    42.18                 6159.44
3        247.83                    45.35                 5638.30
4       1530.36                    54.94                13240.10
...         ...                      ...                     ...
138111   116.50                    51.91                18182.63
138112  1004.89                    44.45                10004.74
138113  1263.27                    55.87                16442.68
138114   953.59                    45.84                 8047.00
138115   678.67                    43.17                 4107.38

       is_repeat_customer customer_order_count
0                    True                   11
1                    True                   11
2                    True                    6
3                    True                    7
4                    True                    8
...                   ...                  ...
138111               True                   14
138112               True                   10
138113               True                   15
138114               True                    5
138115               True                    5

[138116 rows x 46 columns]>

In [35]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()
#Useful during data cleaning when duplicate records are not valid observations.

In [ ]:
df.sort_values("gender", ascending=False)
#Useful for ranking and exploring data.

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
68608,ORD-845420,2024-10-04,20:14:19,Completed,Mobile App,CUST-021493,Craig Hays,63,Non-Binary,Consumer,...,213.41,117.40,63.48,1857.95,1105.80,688.67,37.07,2703.31,True,4
11804,ORD-732492,2025-11-17,14:10:58,Completed,Marketplace,CUST-006428,Jesse Henry,50,Non-Binary,Consumer,...,611.50,312.01,20.21,1892.27,977.61,894.45,47.27,7816.90,True,5
60227,ORD-224540,2023-07-15,11:59:45,Completed,Website,CUST-010088,Melissa Martinez,29,Non-Binary,Consumer,...,376.70,355.39,44.37,2270.20,1030.02,1195.81,52.67,9024.98,True,8
44733,ORD-835608,2024-01-29,00:03:36,Completed,Mobile App,CUST-004857,Maria Peterson,59,Non-Binary,Consumer,...,79.26,67.64,11.62,1045.55,527.34,506.59,48.45,4335.14,True,5
28436,ORD-370015,2021-02-18,14:59:35,Completed,Website,CUST-000540,Carmen Jennings,41,Non-Binary,Consumer,...,517.31,249.32,15.32,3826.31,2554.38,1256.61,32.84,14582.06,True,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82692,ORD-967872,2024-04-01,02:29:19,Completed,Marketplace,CUST-021795,Kevin Carter,63,Female,Consumer,...,0.69,18.01,29.23,304.51,129.08,146.20,48.01,11718.00,True,8
29766,ORD-401076,2021-09-16,14:26:04,Completed,Website,CUST-013620,Michael Clark,31,Female,Consumer,...,85.98,132.87,28.10,825.28,319.65,477.53,57.86,4783.03,True,3
29767,ORD-860832,2023-11-15,16:39:23,Completed,Mobile App,CUST-004798,Katelyn Clark,37,Female,Consumer,...,85.64,15.31,33.37,354.93,198.30,123.26,34.73,8017.49,True,11
82689,ORD-467417,2024-06-02,19:16:27,Completed,Social Media,CUST-009429,Cheryl Franco,26,Female,Business,...,3.27,68.22,23.11,450.39,162.09,265.19,58.88,8338.60,True,8
69058,ORD-537741,2023-06-24,14:49:19,Completed,Mobile App,CUST-002601,Joseph Jones,47,Female,Premium,...,274.50,82.52,18.38,1279.80,542.76,718.66,56.15,11136.13,True,9

In [49]:
df["customer_age"].mean()
# These are useful for understanding numerical variables.

np.float64(45.86268064525471)

In [47]:
df["customer_age"].median()

46.0

In [48]:
df["customer_age"].std()

16.46767571607873

In [50]:
df["customer_age"].min()

18

In [51]:
df["customer_age"].max()

74

In [ ]:
df.groupby("gender")["customer_age"].mean()
#What does it do? 
#Groups data based on a column and allows calculations for each group.

gender
Female        45.815094
Male          45.875460
Non-Binary    46.291860
Name: customer_age, dtype: float64

In [ ]:
df.groupby("gender")["customer_age"].agg(
    ["mean","meadian","min","max"]
)

AttributeError: 'SeriesGroupBy' object has no attribute 'meadian'